apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
  labels:
    app: shopping-cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - name: shopping-cart
          image: zaidevs/shopping:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8070

---

apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: LoadBalancer
